import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { headers } from 'next/headers';

import { ThemeProvider } from 'next-themes';

import NavigationBar from '@/app/(delete-this-and-modify-page.tsx)/NavigationBar';
import '@/app/globals.css';
import { config } from '@/lib/config';
import WagmiProviderComp from '@/lib/wagmi-provider';
import { Toaster } from '@/registry/new-york-v4/ui/sonner';

import { cookieToInitialState } from 'wagmi';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900'
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900'
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

const Layout = ({ children }: Readonly<{ children: ReactNode }>) => {
    // const initialState = cookieToInitialState(config, headers().get('cookie'));

    return (
        <html suppressHydrationWarning lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-background text-foreground overscroll-none antialiased`}>
                <ThemeProvider attribute='class'>
                    <WagmiProviderComp>
                        <NavigationBar />
                        {children}
                        <Toaster />
                    </WagmiProviderComp>
                </ThemeProvider>
            </body>
        </html>
    );
};

export default Layout;
